common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 50
  reconnect: true
  reaping_frequency: 30

credential: &credential
  username: shuttle
  password:

development:
  <<: *common
  database: shuttle_development

test:
  <<: *common
  database: shuttle_test

staging:
  <<: *common
  <<: *credential
  database: shuttle_staging

production:
  <<: *common
  <<: *credential
  database: shuttle_production
